<%@ page contentType="text/html" pageEncoding="UTF-8" %>
<%@ page import = "java.sql.*" %>

<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Database SQL Load</title>
    </head>
    <style>
        .error {
            color: red;
        }
        pre {
            color: green;
        }
    </style>
    <body>
        <h2>Database SQL Load</h2>
        <%
            /* How to customize:
             * 1. Update the database name on dbname.
             * 2. Create the list of tables, under tablenames[].
             * 3. Create the list of table definition, under tables[].
             * 4. Create the data into the above table, under data[]. 
             * 
             * If there is any problem, it will exit at the very first error.
             */
            String dbname = "sob_grup_55";
            String schema = "ROOT";
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            /* this will generate database if not exist */
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/" + dbname, "root", "root");
            Statement stmt = con.createStatement();
            
            /* inserting data */
            /* you have to exclude the id autogenerated from the list of columns if you have use it. */
            String data[] = new String[]{
                //"INSERT INTO " + schema + ".TOPIC VALUES (NEXT VALUE FOR TOPIC_GEN, 'Computer Science')",
               // //"INSERT INTO " + schema + ".USERS (ID, NAME, TELEPHONE, DNI) VALUES (NEXT VALUE FOR User_gen, 'Nicolas', '123456789', '12345678A')",
               // //"INSERT INTO ROOT.CREDENTIALS (ID, USERNAME, PASSWORD) VALUES (NEXT VALUE FOR Credentials_Gen, 'nicolas', '1234')",
               // //"INSERT INTO " + schema + ".USERS (ID, NAME, TELEPHONE, DNI) VALUES (NEXT VALUE FOR User_gen, 'Laura', '987654321', '11223344B')",
                
                
               // //"INSERT INTO " + schema + ".ARTICLES (ID, TITLE, CONTENT, PUBLICATIONDATE, VIEWCOUNT, TOPICS, ISPRIVATE, AUTHOR_ID) " +
               // //"VALUES (NEXT VALUE FOR Article_gen, 'Learning Java', 'A comprehensive guide to Java programming.', CURRENT_TIMESTAMP, 0, 'Programming,Java', 0, 50)"

                //"INSERT INTO " + schema + ".ARTICLES (ID, TITLE, CONTENT, PUBLICATIONDATE, VIEWCOUNT, TOPICS, ISPRIVATE, AUTHOR_ID) " +
                //"VALUES (NEXT VALUE FOR Article_gen, 'Blockchain Basics', 'Understanding the basics of blockchain technology.', CURRENT_TIMESTAMP, 0, 'Blockchain,Finance', 1, 2)"
                //"INSERT INTO " + schema + ".COMMENT VALUES (NEXT VALUE FOR COMMENT_GEN, 'Skeleton code', 1)",
                //"INSERT INTO " + schema + ".COMMENT VALUES (NEXT VALUE FOR COMMENT_GEN, 'for homework1', 1)",
                //"INSERT INTO " + schema + ".CREDENTIALS VALUES (NEXT VALUE FOR CREDENTIALS_GEN, 'sob', 'sob')"
                    
                 "INSERT INTO " + schema + ".USERS (ID, NAME, TELEPHONE, DNI) VALUES (NEXT VALUE FOR User_gen, 'Nicolas', '123456789', '12345678A')",
                "INSERT INTO " + schema + ".CREDENTIALS (ID, USERNAME, PASSWORD) VALUES (NEXT VALUE FOR Credentials_Gen, 'nicolas', '1234')",

                "INSERT INTO " + schema + ".USERS (ID, NAME, TELEPHONE, DNI) VALUES (NEXT VALUE FOR User_gen, 'Laura', '987654321', '11223344B')",
                "INSERT INTO " + schema + ".CREDENTIALS (ID, USERNAME, PASSWORD) VALUES (NEXT VALUE FOR Credentials_Gen, 'laura', '5678')",

                "INSERT INTO " + schema + ".USERS (ID, NAME, TELEPHONE, DNI) VALUES (NEXT VALUE FOR User_gen, 'Pablo', '678912345', '99887766C')",
                "INSERT INTO " + schema + ".CREDENTIALS (ID, USERNAME, PASSWORD) VALUES (NEXT VALUE FOR Credentials_Gen, 'pablo', 'abcd')",

                "INSERT INTO " + schema + ".USERS (ID, NAME, TELEPHONE, DNI) VALUES (NEXT VALUE FOR User_gen, 'Ana', '432156789', '11223355D')",
                "INSERT INTO " + schema + ".CREDENTIALS (ID, USERNAME, PASSWORD) VALUES (NEXT VALUE FOR Credentials_Gen, 'ana', 'efgh')",

                "INSERT INTO " + schema + ".USERS (ID, NAME, TELEPHONE, DNI) VALUES (NEXT VALUE FOR User_gen, 'Carlos', '912345678', '66778899E')",
                "INSERT INTO " + schema + ".CREDENTIALS (ID, USERNAME, PASSWORD) VALUES (NEXT VALUE FOR Credentials_Gen, 'carlos', 'ijkl')",

                "INSERT INTO ROOT.ARTICLES (ID, TITLE, CONTENT, PUBLICATIONDATE, VIEWCOUNT, TOPICS, ISPRIVATE, AUTHOR_ID) " +
                "VALUES (NEXT VALUE FOR Article_gen, 'Learning Java', 'A comprehensive guide to Java programming.', CURRENT_TIMESTAMP, 0, 'Programming,Java', 0, 50)",

                "INSERT INTO ROOT.ARTICLES (ID, TITLE, CONTENT, PUBLICATIONDATE, VIEWCOUNT, TOPICS, ISPRIVATE, AUTHOR_ID) " +
                "VALUES (NEXT VALUE FOR Article_gen, 'Blockchain Basics', 'Understanding blockchain technology.', CURRENT_TIMESTAMP, 0, 'Blockchain,Finance', 0, 100)",

                "INSERT INTO ROOT.ARTICLES (ID, TITLE, CONTENT, PUBLICATIONDATE, VIEWCOUNT, TOPICS, ISPRIVATE, AUTHOR_ID) " +
                "VALUES (NEXT VALUE FOR Article_gen, 'AI Trends', 'Exploring the latest in artificial intelligence.', CURRENT_TIMESTAMP, 0, 'AI,Technology', 0, 100)",

                "INSERT INTO ROOT.ARTICLES (ID, TITLE, CONTENT, PUBLICATIONDATE, VIEWCOUNT, TOPICS, ISPRIVATE, AUTHOR_ID) " +
                "VALUES (NEXT VALUE FOR Article_gen, 'Data Science Essentials', 'Fundamentals of data science.', CURRENT_TIMESTAMP, 0, 'Data,Science', 0, 100)",

                "INSERT INTO ROOT.ARTICLES (ID, TITLE, CONTENT, PUBLICATIONDATE, VIEWCOUNT, TOPICS, ISPRIVATE, AUTHOR_ID) " +
                "VALUES (NEXT VALUE FOR Article_gen, 'Cybersecurity Basics', 'Tips for staying secure online.', CURRENT_TIMESTAMP, 0, 'Cybersecurity,Internet', 1, 150)"

            };
            for (String datum : data) {
                if (stmt.executeUpdate(datum)<=0) {
                    out.println("<span class='error'>Error inserting data: " + datum + "</span>");
                    return;
                }
                out.println("<pre> -> " + datum + "<pre>");
            }
        %>
        <button onclick="window.location='<%=request.getSession().getServletContext().getContextPath()%>'">Go home</button>
    </body>
</html>
